### ISSUE TITLE
Strange

### ISSUE THREAD

**Issue by FDiskas** [astagi/workerloader-jest-transformer#1]
It reverses expect with actual results. :D
```
	transform: {
		'^.+\\.worker.[t|j]sx?$': 'workerloader-jest-transformer',
		'^.+\\.(ts|js|html)$': 'ts-jest',
	},
```

**Comment by astagi** [comment]
Hi @FDiskas thank you for reporting the issue! Could you please be more specific? I can't understand what kind of problem you're experiencing

**Comment by FDiskas** [comment]
@astagi I'm so sorry about this issue - I need to rest more probably.
